# SF Salaries Exercise 

Welcome to a quick exercise for you to practice your pandas skills! We will be using the [SF Salaries Dataset](https://www.kaggle.com/kaggle/sf-salaries) from Kaggle! Just follow along and complete the tasks outlined in bold below. The tasks will get harder and harder as you go along.

**Import pandas as pd.**

In [1]:
import pandas as pd

**Read Salaries.csv as a dataframe called sal.**

In [2]:
sal = pd.read_csv("./data/salaries.csv")

**Check the head of the DataFrame.**

In [3]:
sal.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

**Use the .info() method to find out how many entries there are.**

In [4]:
sal.info()

<class 'pandas.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  str
 2   JobTitle          148654 non-null  str
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  str
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), str(3)
memory usage: 14.7 MB

**What is the average BasePay ?**

In [6]:
sal["BasePay"].mean()

np.float64(66325.44884048769)

**What is the highest amount of OvertimePay in the dataset?**

In [7]:
sal["OvertimePay"].max()

np.float64(245131.88)

**What is the job title of  JOSEPH DRISCOLL ? Note: Use all caps, otherwise you may get an answer that doesn't match up (there is also a lowercase Joseph Driscoll).**

In [8]:
sal[sal["EmployeeName"] == "JOSEPH DRISCOLL"]["JobTitle"]

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: str

**How much does JOSEPH DRISCOLL make (including benefits)?**

In [10]:
sal[sal["EmployeeName"] == "JOSEPH DRISCOLL"]["TotalPayBenefits"]

24    270324.91
Name: TotalPayBenefits, dtype: float64

**What is the name of highest paid person (including benefits)?**

In [17]:
highest_pay_idx = sal["TotalPayBenefits"].argmax()
sal.iloc[highest_pay_idx].reset_index()

               index                                               0
0                 Id                                               1
1       EmployeeName                                  NATHANIEL FORD
2           JobTitle  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY
3            BasePay                                       167411.18
4        OvertimePay                                             0.0
5           OtherPay                                       400184.25
6           Benefits                                             NaN
7           TotalPay                                       567595.43
8   TotalPayBenefits                                       567595.43
9               Year                                            2011
10             Notes                                             NaN
11            Agency                                   San Francisco
12            Status                                             NaN

**What is the name of lowest paid person (including benefits)? Do you notice something strange about how much he or she is paid?**

In [18]:
lowest_pay_idx = sal["TotalPayBenefits"].argmin()
sal.iloc[lowest_pay_idx].reset_index()

               index                      148653
0                 Id                      148654
1       EmployeeName                   Joe Lopez
2           JobTitle  Counselor, Log Cabin Ranch
3            BasePay                         0.0
4        OvertimePay                         0.0
5           OtherPay                     -618.13
6           Benefits                         0.0
7           TotalPay                     -618.13
8   TotalPayBenefits                     -618.13
9               Year                        2014
10             Notes                         NaN
11            Agency               San Francisco
12            Status                         NaN

**What was the average (mean) BasePay of all employees per year? (2011-2014)?**

In [20]:
sal.groupby("Year").mean(numeric_only=True)["BasePay"]

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64

**How many unique job titles are there?**

In [21]:
sal["JobTitle"].nunique()

2159

**What are the top 5 most common jobs?**

In [36]:
sal["JobTitle"].value_counts().head(5).reset_index()

                       JobTitle  count
0              Transit Operator   7036
1                 Special Nurse   4389
2              Registered Nurse   3736
3  Public Svc Aide-Public Works   2518
4              Police Officer 3   2421

**How many Job Titles were represented by only one person in 2013? (e.g. Job Titles with only one occurence in 2013?)**

In [30]:
s1 = sal[sal["Year"] == 2013]["JobTitle"].value_counts()
s1 = s1[s1 == 1]

display(s1.count())

np.int64(202)

**How many people have the word Chief in their job title? (This is pretty tricky)**

In [33]:
sal["JobTitle"].map(lambda v : 1 if "chief" in str(v).lower() else 0).sum()

np.int64(627)

**Bonus: Is there a correlation between length of the Job Title string and Salary?**

In [34]:
title_len = sal["JobTitle"].map(len)
salary = sal["TotalPayBenefits"]

result = title_len.corr(salary)

display(result)

np.float64(-0.03687844593260673)

# Great Job!